# Generated by Django 5.0.14 on 2026-02-07 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AvailabilitySlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Sunday"),
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                        ],
                        db_index=True,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("max_appointments", models.PositiveIntegerField(default=10)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Availability Slot",
                "verbose_name_plural": "Availability Slots",
                "db_table": "availability_slots",
                "ordering": ["day_of_week", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_number", models.CharField(blank=True, max_length=100)),
                ("qualification", models.CharField(blank=True, max_length=255)),
                ("experience_years", models.PositiveIntegerField(default=0)),
                ("bio", models.TextField(blank=True)),
                (
                    "consultation_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "follow_up_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "slot_duration_minutes",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Duration of each appointment slot in minutes",
                    ),
                ),
                (
                    "max_patients_per_slot",
                    models.PositiveIntegerField(
                        default=1, help_text="Maximum patients per time slot"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_accepting_appointments", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Doctor Profile",
                "verbose_name_plural": "Doctor Profiles",
                "db_table": "doctor_profiles",
            },
        ),
        migrations.CreateModel(
            name="SpecificDateAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("max_appointments", models.PositiveIntegerField(default=10)),
                (
                    "is_blocked",
                    models.BooleanField(
                        default=False,
                        help_text="If true, doctor is NOT available on this date",
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "db_table": "specific_date_availability",
                "ordering": ["date", "start_time"],
            },
        ),
    ]
